[package]
name = "slacklog"
version = "0.1.0"
authors = ["Hitoshi Nakashima <morygonzalez@gmail.com>"]
edition = "2018"

[lib]

name = "slacklog"
path = "src/slacklog/lib.rs"

[[bin]]

name = "server"
test = false
doc = false

[dependencies]

rocket = '0.4.0'
